{{- if .Values.route.enabled -}}
{{- $fullName := include "base-package.fullname" . -}}
{{- $root := . -}}
{{- $svcPort := .Values.service.port -}}
{{- range .Values.route.hosts }}
{{- $host := .host }}
{{- range .paths }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ printf "%s-%s" $fullName (.path | replace "/" "-" | trimPrefix "-" | default "root") | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "base-package.labels" $root | nindent 4 }}
  {{- with $root.Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  host: {{ $host | quote }}
  path: {{ .path }}
  to:
    kind: Service
    name: {{ .serviceName | default $fullName }}
  port:
    targetPort: {{ .port | default $svcPort }}
  {{- if $root.Values.route.tls }}
  tls:
    termination: {{ $root.Values.route.tls.termination | default "edge" }}
    insecureEdgeTerminationPolicy: {{ $root.Values.route.tls.insecureEdgeTerminationPolicy | default "Redirect" }}
  {{- end }}
{{- end }}
{{- range .restrictedPaths }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ printf "%s-limit-%s" $fullName (.path | replace "/" "-" | trimPrefix "-" | default "root") | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "base-package.labels" $root | nindent 4 }}
  annotations:
    {{- with $root.Values.route.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    haproxy.router.openshift.io/ip_whitelist: {{ .whitelist | quote }}
spec:
  host: {{ $host | quote }}
  path: {{ .path }}
  to:
    kind: Service
    name: {{ .serviceName | default $fullName }}
  port:
    targetPort: {{ .port | default $svcPort }}
  {{- if $root.Values.route.tls }}
  tls:
    termination: {{ $root.Values.route.tls.termination | default "edge" }}
    insecureEdgeTerminationPolicy: {{ $root.Values.route.tls.insecureEdgeTerminationPolicy | default "Redirect" }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
