{{- if .Values.route.enabled -}}
{{- $fullName := include "base-package.fullname" . -}}
{{- range .Values.route.hosts }}
{{- $host := .host }}
{{- range .paths }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $fullName }}-{{ .path | replace "/" "-" | trimPrefix "-" | default "root" }}
  labels:
    {{- include "base-package.labels" $ | nindent 4 }}
  {{- with $.Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  host: {{ $host | quote }}
  path: {{ .path }}
  to:
    kind: Service
    name: {{ .serviceName | default $fullName }}
  port:
    targetPort: {{ .port | default $.Values.service.port }}
  {{- if $.Values.route.tls }}
  tls:
    termination: {{ $.Values.route.tls.termination | default "edge" }}
    insecureEdgeTerminationPolicy: {{ $.Values.route.tls.insecureEdgeTerminationPolicy | default "Redirect" }}
  {{- end }}
{{- end }}
{{- if .restrictedPaths }}
{{- range .restrictedPaths }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $fullName }}-restricted-{{ .path | replace "/" "-" | trimPrefix "-" }}
  labels:
    {{- include "base-package.labels" $ | nindent 4 }}
  annotations:
    {{- with $.Values.route.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    haproxy.router.openshift.io/ip_whitelist: {{ .whitelist | quote }}
spec:
  host: {{ $host | quote }}
  path: {{ .path }}
  to:
    kind: Service
    name: {{ .serviceName | default $fullName }}
  port:
    targetPort: {{ .port | default $.Values.service.port }}
  {{- if $.Values.route.tls }}
  tls:
    termination: {{ $.Values.route.tls.termination | default "edge" }}
    insecureEdgeTerminationPolicy: {{ $.Values.route.tls.insecureEdgeTerminationPolicy | default "Redirect" }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
